# Generated by Django 4.0.1 on 2022-12-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_message_room_posts_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
